# -*- coding: utf-8 -*-
"""hunarshalaa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfsE182Vt7xoy5qJgG17AG9tMUEJ5lk5
"""

#!pip install kora -q

#!pip install bs4

#from beautifulsoup4 import BeautifulSoup

#from kora.selenium import wd
wd.get("https://tokboard.com/")

wd.page_source

page= wd.page_source
print(page)


soup = BeautifulSoup(page, 'html5lib')

table = soup.find('a', attrs = {'class':'jsx-3696330819'}).text 
print(table)

print (table)

texts = soup.find_all('a', attrs = {'class':'jsx-3696330819'})

print(texts)